//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDetail
    {
        public int Userid { get; set; }
        public string UPassword { get; set; }
        public string Sname { get; set; }
        public string Phno { get; set; }
        public string SAddress { get; set; }
        public string Mailid { get; set; }
        public string FatherName { get; set; }
        public string FatherDesignation { get; set; }
        public string FatherPhNum { get; set; }
        public string MotherName { get; set; }
        public string MotherDesignation { get; set; }
        public string MotherPhNum { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string BloodGrp { get; set; }
        public Nullable<System.DateTime> DateOfJoining { get; set; }
        public string Domain { get; set; }
        public int Syear { get; set; }
        public string Roll_Number { get; set; }
    }
}
